services:
  app:
    image: elmouhoussama/jira-scrum:prod
    container_name: jira-scrum-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: change-me
      DATABASE_URL: file:/data/prod.db
    volumes:
      - prod_data:/data

volumes:
  prod_data:
