name: CD Docker (Build & Push)

on:
  push:
    branches: [ develop, main ]
    tags: [ "v*" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define image tag
        id: vars
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "IMAGE_TAG=dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "IMAGE_TAG=prod" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            echo "IMAGE_TAG=${VERSION}" >> $GITHUB_OUTPUT
            echo "IS_VERSION=true" >> $GITHUB_OUTPUT
          fi

      - name: Ensure IMAGE_TAG is set
        run: |
          if [[ -z "${{ steps.vars.outputs.IMAGE_TAG }}" ]]; then
            echo "ERROR: IMAGE_TAG not set"
            exit 1
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/jira-scrum:${{ steps.vars.outputs.IMAGE_TAG }}

      - name: Push latest tag (release only)
        if: steps.vars.outputs.IS_VERSION == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/jira-scrum:latest
