name: CD Docker (Build & Push)

on:
  push:
    branches: [ main, develop ]
    tags: [ "v*" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Connexion Docker Hub (ou GHCR)
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # DÃ©finir le tag selon la branche
      - name: Define image tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "IMAGE_TAG=dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "IMAGE_TAG=prod" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            echo "IMAGE_TAG=${VERSION}" >> $GITHUB_OUTPUT
            echo "IS_VERSION=true" >> $GITHUB_OUTPUT
          fi

      # Build + Push
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/jira-scrum:${{ steps.vars.outputs.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/jira-scrum:${{ github.sha }}

      # Bonus: latest seulement pour les tags version
      - name: Push latest tag
        if: steps.vars.outputs.IS_VERSION == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/jira-scrum:latest
